# hello-nginx-deployment.yaml
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "20.61.73.190"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-dns-test-01"
spec:
  selector:
    app: hello-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
